# Generated by Django 2.2.4 on 2019-12-19 15:33

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictax_group', to='otree.Session')),
            ],
            options={
                'db_table': 'publictax_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publictax_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'publictax_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('treat', otree.db.models.StringField(max_length=10000, null=True)),
                ('accept_conditions', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('captcha', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('accept_important', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('Instr1', otree.db.models.IntegerField(choices=[[1, 'True'], [2, 'False']], null=True)),
                ('Instr2', otree.db.models.IntegerField(choices=[[1, 'True'], [2, 'False']], null=True)),
                ('Instr3', otree.db.models.IntegerField(choices=[[1, 'True'], [2, 'False']], null=True)),
                ('Instr4', otree.db.models.IntegerField(choices=[[1, 'True'], [2, 'False']], null=True)),
                ('Instr5', otree.db.models.IntegerField(choices=[[1, 'True'], [2, 'False']], null=True)),
                ('timer_id', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('FL1', otree.db.models.IntegerField(choices=[[1, 'More than $102'], [2, 'Exactly $102'], [3, 'Less than $102'], [4, "I don't know"]], null=True, verbose_name='Suppose you had $100 in a savings account and the interest rate was 2% per year. After 5 years, how much do you think you would have in the account if you left the money to grow?')),
                ('FL2', otree.db.models.IntegerField(choices=[[1, 'More than $200'], [2, 'Exactly $200'], [3, 'Less than $200'], [4, "I don't know"]], null=True, verbose_name='Suppose you had $100 in a savings account and the interest rate is 20% per year and you never withdraw money or interest payments. After 5 years, how much would you have on this account in total?')),
                ('FL3', otree.db.models.IntegerField(choices=[[1, 'More than today'], [2, 'Exactly the same as today'], [3, 'Less than today'], [4, "I don't know"]], null=True, verbose_name='Imagine that the interest rate on your savings account was 1% per year and inflation was 2% per year. After 1 year, how much would you be able to buy with the money in this account?')),
                ('FL4', otree.db.models.IntegerField(choices=[[1, 'My friend'], [2, 'His sibling'], [3, 'They are equally rich'], [4, "I don't know"]], null=True, verbose_name='Assume a friend inherits $10,000 today and his sibling inherits $10,000 three years from now. Assume both your friend and his sibling do not spend the $10,000. Who is richer because of the inheritance?')),
                ('FL5', otree.db.models.IntegerField(choices=[[1, 'More than today'], [2, 'Exactly the same'], [3, 'Less than today'], [4, "I don't know"]], null=True, verbose_name='Suppose that in the year 2020, your income has doubled, and prices of all goods have doubled too. In 2020, how much will you be able to buy with your income?')),
                ('australia_check', otree.db.models.IntegerField(choices=[[1, 'The statutory tax rate in Olmeos is 24%'], [2, "The statutory tax rate in Olmeos is 24% and a table containing Alophonica's Revenues, Profit Before Tax, and Corporate Taxes Paid in Olmeos"], [3, "I don't know"]], null=True, verbose_name="In addition to Alophonica's financial report which you could reveal by pressing the button, what else was disclosed?")),
                ('taxmanagement_check', otree.db.models.IntegerField(choices=[[1, 'Shifting profits to countries with a lower statutory tax rate'], [2, 'Using investment tax credits'], [3, 'Both shifting profits and using investment tax credits'], [4, 'Alophonica did not use a tax management strategy’'], [5, "I don't know"]], null=True, verbose_name='Which tax management strategy did Alophonica follow to pay less than the statutory tax rate?')),
                ('assessments_confident', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I am confident about the assessments about Telecom Co. I made on the previous screens.')),
                ('assessments_random', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I made my assessments on the previous screens in a more or less random way.')),
                ('assessments_no_use', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I did not really know how I should use the financial information to make my assessments.')),
                ('fair_rd', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='In general, I consider it fair if companies lower taxes by using investment tax credits.')),
                ('fair_ps', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='In general, I consider it fair if companies lower taxes by shifting profits to countries with a lower statutory tax rate.')),
                ('fair_more', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='In general, I consider it fairer if companies lower taxes by shifting profits to countries with a lower statutory tax rate than when companies use investment tax credits.')),
                ('tax_advisor', otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name='How often do you consult a tax advisor, both privately and as part of your job?')),
                ('TA_1', otree.db.models.IntegerField(choices=[[1, 'Very untrue of what I believe'], [2, 'Untrue of what I believe'], [3, 'Somewhat untrue of what I believe'], [4, 'Neutral'], [5, 'Somewhat true of what I believe'], [6, 'True of what I believe'], [7, 'Very true of what I believe']], null=True, verbose_name='Cheating on taxes if one had the chance is justified.')),
                ('TA_2', otree.db.models.IntegerField(choices=[[1, 'Very untrue of what I believe'], [2, 'Untrue of what I believe'], [3, 'Somewhat untrue of what I believe'], [4, 'Neutral'], [5, 'Somewhat true of what I believe'], [6, 'True of what I believe'], [7, 'Very true of what I believe']], null=True, verbose_name='Claiming state benefits to which one is not entitled is justified.')),
                ('TA_3', otree.db.models.IntegerField(choices=[[1, 'Very untrue of what I believe'], [2, 'Untrue of what I believe'], [3, 'Somewhat untrue of what I believe'], [4, 'Neutral'], [5, 'Somewhat true of what I believe'], [6, 'True of what I believe'], [7, 'Very true of what I believe']], null=True, verbose_name='Reducing taxes by using legal means is justified.')),
                ('taxmanagement_important', otree.db.models.IntegerField(choices=[[1, 'Not at all important'], [2, 'Low importance'], [3, 'Slightly important'], [4, 'Moderately important'], [5, 'Important'], [6, 'Very important'], [7, 'Extremely important']], null=True, verbose_name="How important do you consider a company's tax management strategy when developing your overall opinion about a company?")),
                ('fin_exp', otree.db.models.IntegerField(choices=[[1, 'Not at all familiar'], [2, 'Slightly familiar'], [3, 'Somewhat familiar'], [4, 'Moderately familiar'], [5, 'Extremely familiar']], null=True, verbose_name='How familiar are you with conducting trades and transactions with financial assets such as debt securities, bonds, shares, financial funds, and derivatives.')),
                ('fin_own', otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name='I own or have indirectly or directly owned financial assets such as debt securities, bonds, shares, mutual or pension funds, and derivatives.')),
                ('tax_exp', otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name='I have been involved in developing tax management policies and setting out tax strategies for companies.')),
                ('tax_fam', otree.db.models.IntegerField(choices=[[1, 'Not at all familiar'], [2, 'Slightly familiar'], [3, 'Somewhat familiar'], [4, 'Moderately familiar'], [5, 'Extremely familiar']], null=True, verbose_name="How familiar are you with analyzing and evaluating companies' tax management strategies and policies?")),
                ('tax_freq', otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name="How often do you look at a company's tax management strategy and policy when developing your opinion about a company?")),
                ('gender', otree.db.models.IntegerField(choices=[[1, 'Male'], [2, 'Female'], [3, 'Other'], [4, 'I prefer not to say']], null=True, verbose_name='Please select which gender you identify most with.')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Please enter your age.')),
                ('nationality', otree.db.models.IntegerField(choices=[[1, 'North-America'], [2, 'Central and South-America'], [3, 'Asia'], [4, 'Europe'], [5, 'Australia and Oceania'], [6, 'Africa'], [7, 'I prefer not to say']], null=True, verbose_name='Please select your region of residence.')),
                ('employment', otree.db.models.IntegerField(choices=[[1, 'Working full-time'], [2, 'Working part-time'], [3, 'Unemployed and looking for work'], [4, 'Unemployed and not looking for work'], [5, 'Retired'], [6, 'Student'], [7, 'I prefer not to say']], null=True, verbose_name='Please select what best describes your current employment status.')),
                ('education', otree.db.models.IntegerField(choices=[[1, 'Less than High school'], [2, 'High school'], [3, 'Vocational or trade school'], [4, '2-year College'], [5, '4-year College (BS, BA, or similar)'], [6, 'Postgraduate (MS, MA, PhD, MBA, MD, etc.)'], [7, 'I prefer not to say']], null=True, verbose_name='What is the highest level of education that you have completed?')),
                ('workexperience', otree.db.models.IntegerField(choices=[[1, 'I do not have work experience.'], [2, 'Less than 5 year work experience.'], [3, 'Between 5 and less than 10 years of work experience'], [4, 'Between 10 and less than 20 years work experience.'], [5, 'Between 20 and less than 30 years work experience.'], [6, 'Between 30 and less than 40 years work experience.'], [7, '40 years or more work experience.']], null=True, verbose_name='Please indicate your work experience. All jobs count, including part-time and volunteer work.')),
                ('english', otree.db.models.IntegerField(null=True, verbose_name='Please rate your English on a percentage scale between 0 and 100.')),
                ('politics', otree.db.models.IntegerField(choices=[[1, 'Democrats'], [2, 'Republicans'], [3, 'Other'], [4, 'Prefer not to say']], null=True, verbose_name='Please indicate which political party best describes your political orientation.')),
                ('attention_1', otree.db.models.IntegerField(choices=[[1, 'box'], [2, 'crow'], [3, 'flee'], [4, 'car']], null=True, verbose_name='What rhymes on tree?')),
                ('norm_1', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='When buying products, I generally purchase those brands that I think others will approve of.')),
                ('norm_2', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='If other people can see me using a product, I often purchase the brand they expect me to buy.')),
                ('norm_3', otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I achieve a sense of belonging by purchasing the same products and brands that others purchase.')),
                ('i_judge_1', otree.db.models.FloatField(default=0, null=True)),
                ('check_i_judge_1', otree.db.models.FloatField(blank=True, null=True)),
                ('i_judge_2', otree.db.models.FloatField(default=0, null=True)),
                ('check_i_judge_2', otree.db.models.FloatField(blank=True, null=True)),
                ('i_judge_3', otree.db.models.FloatField(default=0, null=True)),
                ('check_i_judge_3', otree.db.models.FloatField(blank=True, null=True)),
                ('i_market', otree.db.models.FloatField(default=0, null=True)),
                ('check_i_market', otree.db.models.FloatField(blank=True, null=True)),
                ('alotax', otree.db.models.FloatField(default=50, null=True)),
                ('check_alotax', otree.db.models.FloatField(blank=True, null=True)),
                ('mturk', otree.db.models.IntegerField(blank=True, choices=[[1, 'Extremely easy'], [2, 'Moderately easy'], [3, 'Slightly easy'], [4, 'Neither easy nor difficult'], [5, 'Slightly difficult'], [6, 'Moderately difficult'], [7, 'Extremely difficult']], null=True, verbose_name='How difficult was this study?')),
                ('mturk_feedback', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Do you have any feedback for us or anything you would like to say to us?')),
                ('mturk_motivation', otree.db.models.IntegerField(choices=[[1, 'Extremely unmotivated'], [2, 'Very unmotivated'], [3, 'Unmotivated'], [4, 'Neutral'], [5, 'Motivated'], [6, 'Very motivated'], [7, 'Extremely motivated']], null=True, verbose_name='How motivated were you during this study?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publictax.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictax_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publictax_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publictax.Subsession')),
            ],
            options={
                'db_table': 'publictax_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publictax.Subsession'),
        ),
    ]
