# Generated by Django 2.2.4 on 2019-12-18 14:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tax_exp',
            field=otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name='I have been involved in developing tax management policies and setting out tax strategies for companies.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tax_fam',
            field=otree.db.models.IntegerField(choices=[[1, 'Not at all familiar'], [2, 'Slightly familiar'], [3, 'Somewhat familiar'], [4, 'Moderately familiar'], [5, 'Extremely familiar']], null=True, verbose_name="How familiar are you with analyzing and evaluating companies' tax management strategies and policies?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='tax_freq',
            field=otree.db.models.IntegerField(choices=[[1, 'Never'], [2, 'Very rarely'], [3, 'Rarely'], [4, 'Sometimes'], [5, 'Occasionally'], [6, 'Frequently'], [7, 'Very frequently']], null=True, verbose_name="How often do you look at a company's tax management strategy and policy when developing your opinion about a company?"),
        ),
    ]
