# Generated by Django 2.2.4 on 2019-12-19 16:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='australia_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Nothing'], [2, "A table containing Alophonica's Revenues, Profit Before Tax, and Corporate Taxes Paid in Olmeos"], [2, "A table containing Alophonica's Revenues, Profit Before Tax, and Corporate Taxes Paid in Olmeos"], [3, "I don't know"]], null=True, verbose_name="In addition to Alophonica's financial report which you could reveal by pressing the button, what else was disclosed?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='taxmanagement_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Shifting profits to countries with a lower statutory tax rate'], [2, 'Using investment tax credits'], [3, 'Both shifting profits and using investment tax credits'], [4, 'Alophonica did not use a tax management strategy’'], [5, "I don't know"]], null=True, verbose_name='Which tax management strategy did Alophonica follow to pay less than the tax rate?'),
        ),
    ]
