# Generated by Django 2.2.4 on 2019-12-19 14:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0002_auto_20191218_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assessments_confident',
            field=otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I am confident about the assessments about Telecom Co. I made on the previous screens.'),
        ),
        migrations.AddField(
            model_name='player',
            name='assessments_no_use',
            field=otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I did not really know how I should use the financial information to make my assessments.'),
        ),
        migrations.AddField(
            model_name='player',
            name='assessments_random',
            field=otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='I made my assessments on the previous screens in a more or less random way.'),
        ),
        migrations.AddField(
            model_name='player',
            name='taxmanagement_important',
            field=otree.db.models.IntegerField(choices=[[1, 'Not at all important'], [2, 'Low importance'], [3, 'Slightly important'], [4, 'Moderately important'], [5, 'Important'], [6, 'Very important'], [7, 'Extremely important']], null=True, verbose_name="How important do you consider a company's tax management strategy when developing your overall opinion about a company?"),
        ),
    ]
