# Generated by Django 2.2.4 on 2019-12-19 16:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0002_auto_20191219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='australia_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Nothing'], [2, 'A table containing Revenues, Profit Before Tax, and Corporate Taxes'], [3, "I don't know"]], null=True, verbose_name="In addition to Alophonica's financial report which you could reveal by pressing the button, what else was disclosed?"),
        ),
    ]
