# Generated by Django 2.2.4 on 2019-12-19 16:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0003_auto_20191219_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='australia_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Nothing'], [2, 'A table containing Revenues, Profit Before Tax, and Corporate Taxes'], [3, "I don't know"]], null=True, verbose_name="In addition to Telecom Co.'s financial report which you could reveal by pressing the button, what else was disclosed?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='fair_more',
            field=otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='In general, I consider it fairer if companies lower taxes by shifting profits to countries with a lower tax rate than when companies use investment tax credits.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fair_ps',
            field=otree.db.models.IntegerField(choices=[[1, 'Strongly disagree'], [2, 'Disagree'], [3, 'Somewhat disagree'], [4, 'Neither agree nor disagree'], [5, 'Somewhat agree'], [6, 'Agree'], [7, 'Strongly agree']], null=True, verbose_name='In general, I consider it fair if companies lower taxes by shifting profits to countries with a lower tax rate.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='taxmanagement_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Shifting profits to countries with a lower tax rate'], [2, 'Using investment tax credits'], [3, 'Both shifting profits and using investment tax credits'], [4, 'Telecom Co. did not use a tax management strategy’'], [5, "I don't know"]], null=True, verbose_name='Which tax management strategy did Telecom Co. follow to pay less than the tax rate?'),
        ),
    ]
