# Generated by Django 2.2.4 on 2019-12-21 10:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0004_auto_20191219_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='completion_code',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
