# Generated by Django 2.2.4 on 2019-12-21 10:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0005_player_completion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='workexperience',
            field=otree.db.models.IntegerField(choices=[[1, 'I do not have work experience.'], [2, 'Less than 5 years work experience.'], [3, '5 to 10 years of work experience'], [4, '10 to 20 years work experience.'], [5, '20 to 30 years work experience.'], [6, '30 to 40 years work experience.'], [7, '40 years or more work experience.']], null=True, verbose_name='Please indicate your work experience. All jobs count, including part-time and volunteer work.'),
        ),
    ]
