# Generated by Django 2.2.4 on 2020-03-05 13:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0006_auto_20191221_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='etr',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='attention_1',
            field=otree.db.models.IntegerField(choices=[[1, 'box'], [2, 'crow'], [3, 'flee'], [4, 'car']], null=True, verbose_name='What rhymes with tree?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='australia_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Nothing'], [2, 'A table containing Revenues, Profit Before Tax, and Corporate Taxes'], [3, "I don't know"]], null=True, verbose_name="In addition to Telecom Co.'s financial report, which you could reveal by pressing the button, what else was disclosed?"),
        ),
    ]
